name: Tests

on: push

jobs:
  basic_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install clang-format
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format libgraphviz-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools
          pip install .[dev]
      - name: Update git submodules
        run: git submodule update --init --recursive
      - name: C++ lint
        run: |
          python third_party/run-clang-format/run-clang-format.py \
          polytracker/include/polytracker/*.h polytracker/include/taintdag/*.{h,hpp} \
          polytracker/src/passes/*.cpp polytracker/src/polytracker/*.cpp \
          polytracker/src/taint_sources/*.cpp polytracker/src/taintdag/*.cpp
      - name: Python lint/typecheck 
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 polytracker tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 polytracker tests --ignore=F405,F403,W503,E203 --count --exit-zero --max-complexity=30 --max-line-length=127 --statistics
          black --check polytracker tests --exclude '/(polytracker/src|polytracker/scripts)/'
          mypy --python-version ${{ matrix.python-version }} --ignore-missing-imports polytracker tests
      - name: Build the base image
        run: docker build . --file Dockerfile --tag trailofbits/polytracker --no-cache
      - name: PolyTracker tests
        run: |
          pytest
